package com.diya.apps.khatuni.loan.Adapter;

public class ArrayCont {

    public static String[] Que = new String[]{
            "जमीन के प्रकार ",
            "जमीन अदिपत्य के प्रकार",
            "आबादी देह",
            "एकर",
            "अलिनेशन",
            "एनी आर ओ आर",
            "बादस्तूर",
            "बंजर",
            "बंजर जादीद",
            "बंजर कादिम",
            "बारनी",
            "भूमिदार",
            "भूलेख",
            "बीघा",
            "बिस्वा",
            "बिस्वांसी",
            "चारी",
            "चौकीदार",
            "चखोटा",
            "डिट्टम जमाबंदी",
            "ढोली",
            "गैर मुमकिन",
            "गिर्द्वार",
            "गिर्द्वारी",
            "गोशा",
            "हरा भूकटिबंध",
            "गुंठा",
            "हेक्टेयर",
            "हिब्बा (उपहार)",
            "हुजुर जमाबंदी",
            "जवार",
            "कलार",
            "कनाल",
            "कानूनगो",
            "करम",
            "खराबा",
            "खरीफ",
            "खसरा",
            "खसरा गिर्द्वारी",
            "खाता",
            "खतौनी",
            "खेवाट",
            "खेवाट / खतौनी",
            "खुद कशत",
            "किलाबंदी",
            "लम्बरदार",
            "लथा गिर्द्वारी",
            "मार्ला",
            "मस्री",
            "मौज़ा",
            "मिन",
            "मिसाल हकियत",
            "मुसावी",
            "म्यूटेशन",
            "नायब-तहसीलदार",
            "परत पटवार",
            "परत सरकार",
            "पट्टानामा",
            "पटवारी",
            "प्लॅाट",
            "रबी",
            "साबिक",
            "सब डिव्हिजन",
            "सब-डिव्हिजनल मॅजीस्ट्रेट",
            "तबादला ",
            "तक्कावी",
            "तकसीम",
            "तहसीलदार",
            "वारिस",
            "वासिल बाकी नवीस",
            "वट्टर",
            "यार्ड",
            "जमीनदार",
            "क्षेत्र",
            "क्षेत्रीय नक्शा",
            "क्षेत्रीय अध्यादेश",

    };

    public static String[] Ans = new String[]{

           "आबादी\n\nबसा हुआ \n\nबंजर\n\nजिसपर फसल के चार मौसम में खेती न की गई हो. \n\nबरानी\n\nबरसात से सिंचित,\n\nचाही\n\nकुँए अथवा ट्यूब वेल द्वारा सिंचित \n\nचाही नहरी : अंशत \n\nकुए के पानी से और अंशत\n\nगैर मुमकिन\n\nखेती के लिए अनुपयुक्त \n\nनहरी\n\nनाहर के पानी से सिंचित \n",
            "आद्रेहन\n\nकब्जे बगैर गिरवी \n\nगैर दाखिलदार\n\nगैरकानूनी स्थायी आधिपत्य स्थापित करनेवाला (पक्की मुजहिरे)\n\nगैर मरुसी\n\nगैरकानूनी आधिपत्य स्थापित करनेवाला (कच्चे मुजहिरे)\n\nखुद कस्त\n\nस्वामी द्वारा खुद खेती की जानेवाली जमीन \n\\रेहान\n\nकब्जे के साथ गिरवी\n",
            "आबादी देह का मतलब होता है ऐसी कृषि योग्य जमीन, जिसपर गाँव के लोगो ने बस्ती का निर्माण किया हो. (निवास का निर्माण किया हो)",
            "भूमि का इलाका नापने की एक इकाई.",
            " आवंटन .....केरल (राज्य) के जमीन आवंटन नियम 1964 के अनुसार इसमें बिक्री, उपहार (जिसमे वसीयत द्वारा दान भी शामिल हैं), गिरवी रखना, या किराये पर देना भी शामिल हैं.",
            "जमीन संबंधी अधिकार का कोई भी अभिलेख, वह चाहे किसी भी जगह का हो. एनी आर ओ आर:  गुजरात राज्य में इसका मतलब होता है, कम्प्युटर पर दर्ज जमीन संबंधी अधिकार का अभिलेख.",
            "बिना किसी बदलाव के, बिना किसी परिवर्तन के.",
            "अनउपजाऊ जमीन.",
            "ऐसी उपजाऊ जमीन जिसपर अतीत में फसल उगाई गई थी लेकिन लगातार पिछले चार मौसम में खाली पड़ी हैं / रहने दी गई हैं.",
            "ऐसी उपजाऊ जमीन जिसपर अतीत में फसल उगाई गई थी लेकिन अब लगातार पिछले चार मौसम के बाद भी खाली पड़ी हैं / रहने दी गई हैं.",
            "बारिश पर निर्भर.",
            "ऐसा व्यक्ति, जिसके पास किसी जमीन पर खेती करने के अधिकार हैं. ",
            "भारत में जमीन-जायदाद संबंधी दस्तावेजों के लिए हिंदी शब्द.",
            "भूमि का इलाका नापने का एक पैमाना (यह विभिन्न प्रदेशों में अलग अलग होता हैं)",
            "एक बीघे का बीसवा हिस्सा (1/20)",
            "एक बीघे का बीसवा हिस्सा (1/20)",
            "एक प्रकार का मोटा अनाज जिसे पशुओं के खाद्य के तौर पर उगाया जाता हैं.",
            "गाँव का पहरेदार.",
            "किराये के रूप में दिए जानेवाले अनाज का ढेर अथवा बारिश या जाड़े के दिनों में उगाई जानेवाली फसल की किराये के तौर पर दी जानेवाली निश्चित मात्रा.",
            "डिट्टम जमाबंदी को गाँव के तहसीलदार द्वारा गाँव के मुनीम(अकाउंटेंट) द्वारा 1 जुलाई को वार्षिक लेखाजोखा पूर्ण करने के तुरंत बाद संचालित किया जाता हैं.",
            "मृत्यु के समय ब्राह्मण को दिया गया उपहार अथवा भूमि का छोटा सा हिस्सा.",
            "बंजर / अनउपजाऊ जमीन.",
            "माल या राजस्व महकमे का वह क्षेत्रीय अधिकारी जो पटवारियों या लेखपालों के कागज़ात एवं काम-काज की जाँच करता है, इसे हिंदी में कानूनगो भी कहते हैं.",
            "फसल का मुआयना.",
            "कोना.",
            "हरियाली (हरी वनस्पतियाँ) बढाने के लिए सुरखित भूभाग.",
            "जमीन का क्षेत्र नापने का एक पैमाना; 1 गुंठा = 121 वर्ग यार्ड्स = 101.17 वर्ग मीटर.",
            "जमीन का क्षेत्र नापने का पैमाना; 1 हेक्टेयर =2.47 एकर.",
            "जब किसी जमीन का एक हिस्सा किसी व्यक्ति को उपहार में दिया जाता हैं, उस तबदीली को हिब्बा या उपहार कहते हैं. जिस व्यक्ति को भूमि का हिस्सा उपहार में दिया गया हैं, उसका विवरण दर्ज किया जाता हैं.",
            "हुजुर जमाबंदी को उप-आयुक्त (डिप्टी-कमिशनर) या सहायक आयुक्त (असिस्टंट कमिशनर) अथवा उनके द्वारा नियुक्त किसी अधिकारी द्वारा अक्तूबर से दिसंबर माह के बीच संचालित किया जाता हैं, जिसमें विगत वर्ष (पिछले साल) का गाँव का हिसाब सत्यापित कर वर्तमान वर्ष के लिए राजस्व और अन्य वसूली निर्धारित की जाती हैं. यह एक प्रकार से पिछले साल के बही खाते का लेखा परीक्षण (ऑडिट) एवं आंशिक रूप से वर्तमान वर्ष के राजस्व का निरिक्षण कर उन्हें अद्यावत करने जैसा होता हैं.",
            "एक प्रकार का मोटा अनाज जिसे अंग्रेजी में सोरघुम या ग्रेट मिलेट भी कहते हैं.",
            "बंजर / अनउपजाऊ जमीन (खट्टी चिकनी मिट्टी?)",
            "जमीन नापने का एक पैमाना.",
            "पटवारियों का पर्यवेक्षक (सुपरवाइजर)",
            "लम्बाई नापने का एक पैमाना.",
            "फ़ासल का एक हिस्सा जो उगा नहीं.",
            "शरद ऋतू की फसल.",
            "खसरा भारत मी प्रयोग किया जानेवाला खेतीसंबंधी एक कानुनी दस्तावेज हैं, जिसमे खेती की जमीन एवं फसल संबंधी विस्त्तृत विवरण मौजूद होता हैं. परंपरागत खसरे में सारी खेती योग्य जमीन, उसका क्षेत्रफल, नाप (लम्बाई इत्यादि), जमीन का मलिक कौन हैं, उसने फसल उगाने के लिए किसे नियुक्त किया हैं, पैदा की जानेवाली फसल, मिट्टी का प्रकार, जमीन पर कौनसे पेड़ हैं आदि जानकारी होती हैं.",
            "फसल का मुआयना बहीखाता.",
            "काश्तकार द्वारा नियंत्रित ",
            "एक गाँव में स्थित किसी व्यक्ति विशेष अथवा परिवार के स्वामित्व में आनेवाले सारे खेतों के खसरे का संक्षिप्त रूप. या इसे दूसरे शब्दों में कह सकते हैं कि खतौनी में किसी व्यक्ति विशेष अथवा परिवार के स्वामित्व वाले सारे खेतों के खसरे सूचीबद्ध होते हैं.",
            "मलिक के स्वामित्व वाली संपत्ति की सूची.",
            "खेवाट और खतौनी का सम्मिश्रण.",
            "भू-स्वामी द्वारा खुद खेती की जानेवाली जमीन.",
            "आयताकार पैमाइश ",
            "गाँव का मुखिया.",
            "पटवारी के नक़्शे की कपडे पर उतारी गई नक़ल.",
            "क्षेत्रफल का मापन ",
            "एक छोटी दलहन.",
            "गाँव.",
            "अंश /भाग / हिस्सा",
            "अधिकार अभिलेख ",
            "नक्शा बनने में प्रयुक्त कागज़.",
            "मालिकाना हक़ का हस्तांतरण या बदलाव.",
            "तहसीलदार का सहायक या असिस्टंट.",
            "नए अभिलेख निपटारे की पटवारी की प्रतिलिपि  ",
            "नए अभिलेख निपटारे की सरकारी प्रतिलिपि  ",
            "जब कोई जमीन का हिस्सा किसी व्यक्तिको लम्बे समय के लिए किराये पर दिया जाता हैं, उस मालिकाना हक़ में बदलाव को पट्टानामा कहते हैं.",
            "गाँव का मुनीम अथवा पंजीयक (एक सरकारी मुलाजिम जिसपर भूमि के स्वामित्व का लेखाजोखा रखने की जिम्मेदारी होती हैं).",
            "जमीन का छोटा सा टुकड़ा जिसपर हरे भरे पेड़ पौधे उगे हुए हो.",
            "वसंत ऋतू की फसल.",
            "भूतपूर्व ",
            "जिले का उप विभाग.",
            "तहसीलदार का प्रभारी.",
            "तबादला अथवा मालिकाना हक़ में अदलाबदली वह मालिकाना हक़ में बदलाव हैं जिसमे दो स्वामी आपस में अपनी जमीन की अदलाबदली करने को राजी होते हैं. यह (रोझनामचा वकैती द्वारा) केवल मुह-जुबानी (मौखिक) अथवा पंजीकरण द्वारा हो सकता हैं. इसका अंकित विवरण पिछले प्रकरण समान ही यानि रोझनामचा वकैती द्वारा अथवा पंजीकरण द्वारा होता हैं.  नाहर के पानी से सिंचित ",
            "सरकार द्वारा किसी जमीन के स्वामी को खेती के लिए दिया गया कर्ज.",
            "अगर किसी संयुक्त स्वमित्ववाली जमीन का बटवारा होता हैं, तो उस मालिकाना हक़ में बदलाव को तकसीम अथवा बटवारे द्वारा मालिकाना हक़ कहते हैं. यह उसके मालिको में जुबानी सहमती द्वारा अथवा कोर्ट के निर्देश पर हो सकता हैं.",
            "तहसील का प्रभारी.",
            "उत्तराधिकारी ",
            "तहसील के राजस्व का लेखापाल (मुनीम)",
            "तिरछी लकीर ",
            "नापने की एक इकाई. 1 यार्ड = 0.9144 मीटर",
            "भूमि का मलिक ",
            "शहर या नगर के वर्गीकृत खंड जिसमे से कुछ निश्चित उपयोग के लिए आरक्षित हो सकते हैं, जैसे हरियाली के लिए सुरक्षित भू क्षेत्र. ",
            "एक ऐसा नक्शा जिसमे विभिन्न क्षेत्र दर्शाए गए हो.",
            "किसी क्षेत्र विशेष को संचालित करने के नियम एवं अधिनियम ",


                  };


    public static String[] Que_1 = new String[]{

            "Type of Land",
            "Type of Land Possession",
            "Abadi Deh",
            "Acre",
            "Alienation",
            "AnyRoR",
            "Badastur",
            "Banjar",
            "Banjar Jadid",
            "Banjar Kadim",
            "Barani",
            "Bhumidar",
            "Bhoolekh",
            "Bigha",
            "Biswa",
            "Biswansi",
            "Chari",
            "Chaukidar",
            "Chkota",
            "Dittam Jamabandi",
            "Dholi",
            "Gair-Mumkin",
            "Girdawar",
            "Girdawari",
            "Gosha",
            "Green Zone",
            "Guntha",
            "Hectare",
            "Hibba (Gift)",
            "Hujur Jamabandi",
            "Jawar",
            "Kalar",
            "Kanal",
            "Kanungo",
            "Karam",
            "Kharaba",
            "Kharif",
            "Khasra",
            "Khasra Girdawari",
            "Khata",
            "Khatauni",
            "Khewat",
            "Khewat/Khatauni",
            "Khud Kashat",
            "Killabandi",
            "Lamaberdar",
            "Latha Girdawari",
            "Marla",
            "Masri",
            "Mauza",
            "Min",
            "Misal Haqiyat",
            "Musavi",
            "Mutation",
            "Naib-Tehsildar",
            "Parat Patwar",
            "Parat Sarkar",
            "Pattanama",
            "Patwari",
            "Plot",
            "Rabi",
            "Sabik",
            "Sub-Division",
            "Sub-Divisional Magistrate",
            "Tabadala",
            "Taccavi",
            "Takseem",
            "Tehsildar",
            "Waris",
            "Wasil Baqi Nawis",
            "Wattar",
            "Yard",
            "Zamindar",
            "Zone",
            "Zoning Map",
            "Zoning Ordinance",

    };

    public static String[] Ans_1 = new String[]{


                       "Abadi\nInhabited.\n\nBanjar\nNot cultivated from four cropping seasons.\n\nBarani\nRain-fed.\n\nChahi\nIrrigated through wells/tubewells.\n\nChahi Nahri\nIrrigated partly from a well and partly from canal.\n\nGair mumkin\nNon cultivable.\n\nNahri\nIrrigated through Canals.\n",
            "Aadrehan\nmortgage without possession.\n\nGair Dakhildar\nUnauthorised permanent possessioner (pakkee mujahire).\n\nGair Marusi\nUnauthorised possessioner (Kache mujahire).\n\nKhud Kast\nSelf cultivated (Cultivated by the owner himself).\n\nRehan\nmortgage with possession.\n",
            " Abadi Deh refers to cultivable lands which are inhabited by the villagers.",
            "Unit of measurement of land.",
            "Alienation in Kerala Land Assignment Rule 1964 includes sale, gift, (bequest under a will), mortgage, hypothecation or lease.",
            " Any Record of Rights Anywhere. ",
            "Unaltered.",
            "Uncultivated land.",
            "New fellow (correction-the word is fallow) (land not cultivated for continuous four harvests though it was cultivated earlier.",
            "Old fallow (If continued to be uncultivated for next four harvests).",
            "Dependent on rainfall.",
            "An individual who has the right to use land for purposes related to agriculture or farming.",
            "Hindi word related to government documents of land revenue.",
            "A measure of area (It is different in different areas).",
            "One twentieth of a bigha.",
            "One twentieth of a biswa.",
            "A kind of millet (g.v.) grown for fodder.",
            "Village Watchman.",
            "Lump grain rent or rent consisting of a foxed amount of grain in the rabi and kharif.",
            "Dittam jamabandi is conducted by Tahasildar, immediately after the Annual Accounts of a village are completed by the Village Accountant as on 1st July. ",
            "Death bed gift or a small plot of land to a Brahmin.",
            "Barren.",
            "Kanungo or Supervisor of Patwaris.",
            "Harvest Inspection.",
            "Corner.",
            "Area specifically reserved for green vegetation.",
            "Unit of measurement; 1 Gunta = 121 square yards = 101.17 square metres.",
            "A unit of measurement; 1 Hectare=2.47 acres.",
            "Whenever a part of complete land is gifted to some person, the mutation is called Hibba or Gift. The details of the person to whom land has been gifted are recorded.",
            "Hujur Jamabandi is conducted by the Deputy Commissioner or by Asst.Commissioner any other officer appointed as such, between October to December, to verify and settle the village accounts of the previous year and to determine the Land Revenue and other dues for the current year. This is more or less an audit of last year’s account and partly inspection to see that the accounts of the current year are brought up-to-date. Read More.",
            "A kind of millet (Sorghum Val gave).",
            "Barren Land (Sour Clay).",
            "A measure of area.",
            "Supervisor of Patwaris.",
            "Unit of Length.",
            "Portion of crop which has failed to come.",
            "Autumn harvest.",
            " A khasra is a legal agricultural document used in India that specifies land and crop details. Khasras traditionally detail “all the fields and their areas, measurement, who owns and what cultivators he employs, what crops, what sort of soil, what trees are on the land.”",
            "Harvest Inspection Register.",
            "Holding of tenant.",
            " A khatauni is an abstract based on the khasras of a village that lists out all the holdings of an individual or family in that village. In other words, all khasras that belong to a given individual will be listed in the khatauni of that individual.",
            "A list of Owner’s holding.",
            "A combined Khewat & Khatauni.",
            "Cultivated by the owner himself.",
            "Rectangular measurement.",
            "Village Headman.",
            "Cloth copy of the Patwari’s Map.",
            "Measuring of Area.",
            "A small pulse.",
            "Village.",
            "Portion / Part.",
            "Record-of-Right.",
            "Mapping Sheet.",
            "Transfer or change in the ownership title.",
            "The Deputy or Assistant of Tehsildar.",
            "Patwari copy of the new settlement record.",
            "Government Copy of the new settlement record.",
            "Whenever a piece of land is given on lease for a long period, the mutation is known as Pattanama.",
            "A Village Accountant or Registrar (A Government Authority responsible for maintaining land ownership records).",
            "Small segment of land covered with green vegetation.",
            "Spring Harvest.",
            "Former.",
            "A sub division of a district.",
            "In-charge of a tehsildar.",
            "Tabadla or mutation of exchange is the mutation, when two owners decide to exchange their lands. It can Again be either verbal (through Roznamcha Waqaiti) or through Registry. The details recorded are similar as those in the previous case i.e. either through Roznamcha Waqaiti entry or through Registry.",
            "Loan granted by a Government to landowner for agriculture purposes.",
            "Whenever there is a division of land in a joint holding, the mutation is known as Takseem or Mutation of Partition. The partition can be verbal among the landowners or when court directs the partition.",
            "In-charge of a tehsil.",
            "Successor.",
            "Revenue Accountant in the Tehsil.",
            "Diagonal Line.",
            "Unit of measurement; 1 Yard = 0.9144 Meter.",
            "Landowner.",
            "Parts of a city or town categorized into segments some of which may be reserved for a specific purpose such as green zones.",
            "A map indicating the different zonal regions.",
            "Rules and regulations governing a particular zonal area.",


    };



}
